### ISSUE TITLE
Compile Error - undefined reference

### ISSUE THREAD

**Issue by mriggins** [DirectOutput/TeensyStripController#1]
Have my Teensy 3.2 connected,  I'm running the Arduino IDE 1.8.5 with the Teensy Extensions. I set the board to Teensy 3.2/3.1.  When I try to upload the TeensyStripController from 

 https://github.com/D...StripController

 all I get is:

 
C:\Users\Matt\AppData\Local\Temp\arduino_build_655389/core\core.a(main.cpp.o): In function `main':
 
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/main.cpp:51: undefined reference to `setup'
 
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy3/main.cpp:53: undefined reference to `loop'
 
collect2.exe: error: ld returned 1 exit status
 
Error compiling for board Teensy 3.2 / 3.1.
 
 
As as  test I tried File / Examples / TeensyThreads / Blink and that compiled ok.

**Comment by lizardking** [comment]
Soory, I have no idea whats wrong. 

The error messsage complains about not finding the main and the loop methods. These 2 methods are the base methods of every arduino/teensy project.

Since these methods are obviously present in the code, the problem must be somewhere else. As a starting point, you might want to check if the files are in the correct format and readable.

**Comment by mriggins** [comment]
Well the files are the ones I downloaded here lol. Again I'm able to flash the examples no problem, but I get that error when trying the files I downloaded here.

**Comment by mriggins** [comment]
Defragster on the pjrc forums said:

This error is in the build system - nothing to do with the Teensy. With a failed build it has not even looked for a Teensy.

Can you compile a simple Blink.ino or other from examples? If not something corrupted the install, if so then the problem is in the Sketch or associated library files causing conflicts with core files.

**Comment by lizardking** [comment]
Quite honestly I have no idea whats wrong. When I published the code this compiled easily on my system. I've just tried again to compile it on my system and everything works without a problem.

**Comment by mriggins** [comment]
Out of curiosity, nothings changed in the Arduino IDE and Teensydunio that would affect the sketch would it? 

On a side note, I downloaded the compiled TeensyStripController Firmware Beta V1.02 2.1.16 13:51 hex file and uploaded that via the teensy.exe program and that flashed just fine. So in the end, is that precompiled beta any different than the sketch? If not, then I'll just stick with the hex file. :)

**Comment by PaulStoffregen** [comment]
The error is due to copying the wrong file.  Details here:

https://forum.pjrc.com/threads/52764-Teensy-Compile-Problem-in-function-main?p=181854&viewfull=1#post181854

**Comment by lizardking** [comment]
OK, it seems that thios issue has been sorted out. THanks for your comment Paul.
